# Generated by Django 5.1.5 on 2025-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='userId',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
