# Generated by Django 5.1.5 on 2025-01-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactions_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='username',
        ),
    ]
