# Generated by Django 5.1.5 on 2025-02-05 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_transactions_recipient_transactions_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='time',
        ),
        migrations.AddField(
            model_name='transactions',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
